# Generated by Django 6.1.1 on 2026-10-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Only for you, e.g. 'AdSense top' or 'Amazon summer dress banner'.",
                        max_length=80,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("post_top", "Post page: above the article text"),
                            ("post_middle", "Post page: middle of the article"),
                            ("post_end", "Post page: after the article"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide this ad without deleting it.",
                    ),
                ),
                (
                    "ad_code",
                    models.TextField(
                        blank=True,
                        help_text="Paste the full snippet from AdSense or another network.",
                        verbose_name="Ad network code",
                    ),
                ),
                ("banner", models.ImageField(blank=True, upload_to="ads/")),
                ("banner_alt", models.CharField(blank=True, max_length=150)),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="Where the banner points to.",
                        verbose_name="Affiliate link",
                    ),
                ),
            ],
            options={
                "ordering": ["placement"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="has_affiliate_links",
            field=models.BooleanField(
                default=False,
                help_text="Shows an affiliate disclosure at the top of this post.",
            ),
        ),
    ]
