# Generated by Django 6.1.1 on 2026-10-07 06:51

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_adslot_post_has_affiliate_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("about", "About"),
                            ("contact", "Contact"),
                            ("privacy-policy", "Privacy Policy"),
                            ("affiliate-disclosure", "Affiliate Disclosure"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", django_ckeditor_5.fields.CKEditor5Field(verbose_name="Body")),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("show_in_footer", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
